
# 1. Database Connection Parameters
spring.datasource.url=jdbc:mysql://localhost:3306/stock_sync_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Sami@mysql@001

# 2. Driver Engine
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Hibernate Lifecycle Configuration 
# Setting this to 'none' prevents Hibernate from fighting with your custom SQL file
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# 4. Explicitly Run Your Custom schema.sql On Startup
spring.sql.init.mode=always